# Generated by Django 4.0.3 on 2022-04-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
